# https://docs.microsoft.com/en-us/azure/spring-cloud/github-actions-key-vault
# https://github.com/Azure/get-keyvault-secrets
# https://github.com/marketplace/actions/azure-cli-action
name: Scoped credentials test

on: 
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/get-keyvault-secrets@v1
      id: keyvaultaction
      with:
        keyvault: "ghaction-deploy-credscwi"
        secrets: "AZURE-CREDS"
    - uses: azure/login@v1
      with:
        creds: ${{ steps.keyvaultaction.outputs.AZURE-CREDS }}
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az account show
